name: ci
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]

    steps:

      - uses: actions/checkout@v2

      - name: Install rust nightly
        uses: actions-rs/toolchain@v1.0.5
        with:
            toolchain: nightly
            override: true

      - name: Checkout themis.vim
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis

      - name: Add themis to path
        run: |
          echo "::add-path::./vim-themis/bin"

      - uses: rhysd/action-setup-vim@v1.2.0
        id: vim
        with:
          neovim: true
          version: nightly

      - name: Run tests
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
          THEMIS_HOME: ./vim-themis
        run: make test
